### PR TITLE
Added Passenger and Copilot models

### PR DESCRIPTION
**Pull request by hbeni**
Passengers and Copilot for the C182S / C182T :grin: 
- Easily turned off with the standard "show pilot" checkbox in the standard view dialog.
- Only shown if the seats are occupied in the loading dialog.

grafik
grafik

Ready for merge in my view.

### CODE REVIEW

**Comment by hbeni** [comment]
And now MP compatible, too!
grafik

**Comment by HHS81** [comment]
Maybe needs some lightmaps- but I can render them later. I merged it.

**Comment by HHS81** [comment]
Have to reopen- seems I forgot to pull master before I added my changes to fdm and gear.

**Comment by HHS81** [comment]
Fixed- sorry!

**Pull request merged**
