### PR TITLE
Added winterization kit (decreases cooling airflow -> higher temps)

### PR DESCRIPTION
**Pull request by hbeni**
The winter kit reduces cooling airflow, helping keeping the engine warm at cold weather.

image

### CODE REVIEW

**Comment by hbeni** [comment]
Option can be enabled at aircraft options

**Comment by hbeni** [comment]
@gilbertohasnofb Can you make this placard?

**Comment by gilbertohasnofb** [comment]
@hbeni Sure, but what placard? Can you post a picture?

**Comment by gilbertohasnofb** [comment]
@hbeni Ok, I understand what placard you are talking about. I will add it to the cockpit texture tomorrow.

**Comment by gilbertohasnofb** [comment]
@hbeni It turns out the placard is already there:



The position is based on photographs of the cockpit, e.g.:



1b

**Comment by HHS81** [comment]
@hbeni So it can be merged?

**Comment by hbeni** [comment]
@gilbertohasnofb cool! I really overlooked that in the texture, sorry for bothering you without double checking!

@HHS81 I think it is mergeable; however what i'm still unsure about is the oil temperature. Maybe the current setting for the cooling-factor is too efficient, keeping the CHT too low at normal flight. I will play a little more with this okay? I will report back soon.

**Comment by hbeni** [comment]
Ok, since 420fab3 i am much more satisfied with the temps.
Please note, that these temperatures are just guesses, i have no first hand experience.

@HHS81 I think you may merge this now, if you like

**Comment by gilbertohasnofb** [comment]
@hbeni no worries!

**Comment by hbeni** [comment]
@gilbertohasnofb Would it be a good idea to exchange the air-inlet texture when the kit is installed, so one can see visually in the preflight check that the kit is installed?
I don't know how to do this, however. Can you help?

**Comment by gilbertohasnofb** [comment]
@hbeni I would be happy to help, but can you better explain to me what needs to be exchanged? I do not know how the winterization kit looks like and I don't know what needs to be changed texture-wise.

**Comment by hbeni** [comment]
Hello Gilberto, 
unfortunately i was not able to find the exact c182 kit as images.
Basicly it consists of insulation (not visible) and metal plates with slits/holes mounted into the air intake behind he propeller, so the cooling airflow is physically reduced.

The 172 ones look like this: 172 baffles
The slits would be visible when one looks into the vents from the front.

**Comment by hbeni** [comment]
Assuming from the POH-text (see first post) it may also be more like this: Two plates

**Comment by hbeni** [comment]
Assuming from the POH-text (see first post) it may also be more like this: Two plates

**Comment by gilbertohasnofb** [comment]
@hbeni I think I understand now what you mean by exchanging the texture: you mean that instead of creating a 3D model for the winter kit we should simply swap the air inlet texture, so one texture will have the kit and another won't. Is that correct? If so, I think this is not a very good route and I think we should go ahead with 3D modelling. Here are a couple of arguments:

1) it's much easier to simply add/remove a 3D object such as how we do with the wheel chokes
2) having two sets of texture for each livery would be an overkill and would really enlarge this repo
3) the air inlets in the c182s model are true holes (unlike the c172p which are made out of textures), so that the texture route wouldn't work IMO:



With that all said, if you or @HHS81 manage to come up with the 3D model, I would be happy to supply a texture. Would you prefer a dark plastic texture like the bottom one or a grey one like the first image?

Also, with a 3D object, we could make that by clicking on the nose cone the user can add/remove the winterization kit.

**Comment by hbeni** [comment]
I agree a 3d model is better.
We need @HHS81 for that, it seems i cannot learn 3d modelling.

**Comment by gilbertohasnofb** [comment]
I am also terrible at 3D modelling... So if @HHS81 is up to create this model, I would gladly make a texture for it!

**Comment by HHS81** [comment]
I have to see if there is still some place left on the uvmap. I guess we want to have the placard on the Nosecap Cover readable.

**Comment by hbeni** [comment]
Just out of curiosity, would it be possible to add a seperate texture image file? Otherwise all liverys must be redone...

**Comment by gilbertohasnofb** [comment]
@HHS81 If I understood correctly, there is no need for a placard any longer (it's already there in the panel), there is just the winterization kit texture.

**Comment by hbeni** [comment]
@gilbertohasnofb There is also a placard on the winter kit itself which @HHS81 is speaking about

**Comment by HHS81** [comment]
@gilbertohasnofb The Nosecap Cover has also a placard

**Comment by HHS81** [comment]
@hbeni 

> Just out of curiosity, would it be possible to add a seperate texture image file? Otherwise all liverys must be redone...

Would not be wise....

**Comment by gilbertohasnofb** [comment]
> The Nosecap Cover has also a placard

I see.

**Comment by HHS81** [comment]
@hbeni @gilbertohasnofb 
I will add the winterkit 3d-model (aka Nosecap Cover) tomorrow, I think I do know how to add the placard without changing all liveries.

**Comment by gilbertohasnofb** [comment]
Great, I look forward to it!

**Pull request merged**
