### PR TITLE
Issue296 minor corrections

### PR DESCRIPTION
**Pull request by hbeni**
see #296:
- [x] davtron is off now without power
- [x] oil pressure in idle fixed
- [x] cowl smoke briefly after start (mixture too rich because of start)
- [x] tooltips of pitot and air/heat levers each now update on both properties changing
- [x] even better tooltip showing current warmth status

### CODE REVIEW

**Comment by hbeni** [comment]
Alan informed me on a new property: https://forum.flightgear.org/viewtopic.php?p=336544#p336544

I want to use that for calculating smoke, as this will also work in flight with generating exhaust smoke in vety rich conditions

**Comment by hbeni** [comment]
Ok, it unfortunately seems that i will not have time to play with the `/fdm/jsbsim/propulsion/engine/AFR` prop for some time now. I propose we will merge this in the current state, as this is quite good already i think. I will open another issue (see #299) so we have a reminder.

**Comment by hbeni** [comment]
I want to add the current status to the lever tooltip, so pilots can adjust to the right directoon with the cabin messages turned off.

**Comment by hbeni** [comment]
nicer :)
should be really ready to merge now.

**Comment by HHS81** [comment]
Will be merged!

**Comment by HHS81** [comment]
Thanks a lot! 👍

**Pull request merged**
