### PR TITLE
Fog/Frost and Securing: added plane cover implementation

### PR DESCRIPTION
**Pull request by hbeni**
Starting cold&dark in winter with no plane cover makes the plane frosted.
Use the "clean aircraft" button to remove frost and snow.
To prevent, a plane cover ca be applied using the aircraft-securing dialog.

Fog/Frost refactored regarding cleaning/inducing:
- Added /fdm/jsbsim/heat/init-moisture to quick-add fog/frost condition
- Aircraft cleaning button now also removes frost/fog (it's being scraped/wiped away)

----

- [x] Systems additions
- [x] GUI enhancement
- [x] 3D Model of cover (from eagle)
- [x] Make ground startup sim startup with walker outside if cover was applied last session
- [ ] try to frost the cover visually if plane would be frosted, and remove frost of plane with removal of cover

### CODE REVIEW

**Comment by hbeni** [comment]
The last thing needed is a 3D-model of the plane cover (when clicked: remove). The linked property is `/sim/model/c182s/securing/plane-cover-visible` which is already fully hooked up.

**Comment by hbeni** [comment]
@TheFGFSEagle If you need a new 3D endeavour, here we just need a 3D model to complete this feature

**Comment by TheFGFSEagle** [comment]
Um, normally I'd say yes, but sadly I won't have time in the next weeks ! :(

**Comment by TheFGFSEagle** [comment]
Well, I'm currently working on a GNC 255 for the C310, but I guess this would be a welcome distraction ! :D will see if I can do it.

**Comment by hbeni** [comment]
Just merged master into this, so work can more easily go on.
Like said, just the cover's 3D model/artwork is missing.

**Comment by TheFGFSEagle** [comment]
So I was just getting a notification for this pull request (for whatever reason, I don't know …) and just noticed my post where I said  I were working on the GNC255 is already 3 weeks old … 3 weeks ?? It feels like I'm working on it  for maybe one week ! But if you remind me tomorrow 18:00 I can maybe do the cover modelling ! :)

**Comment by TheFGFSEagle** [comment]
Alright, I've started on it - here's some progress:
c182s-cover-pogress

**Comment by wlbragg** [comment]
Cool!

**Comment by TheFGFSEagle** [comment]
@wlbragg if it's not already there I guess I could do the same for the 172 if wanted.

**Comment by hbeni** [comment]
Nice :) +1

Just to get sure - Heiko and I are aiming for something like  this: https://www.sky4pilots.co.uk/product/cessna-182-cockpit-engine-wm80/
grafik

**Comment by TheFGFSEagle** [comment]
Ok, I was working along https://www.aircraftcovers.com/media/images/24199.jpg but I can also add the front part from your pic, no problem.

**Comment by hbeni** [comment]
Or... maybe even this:
https://aerocovers.com/wp-content/uploads/2020/05/01_wing_covers_allseason.jpg
grafik


Reason: This way we elegantly avoid the icing animation on the wings :)

**Comment by TheFGFSEagle** [comment]
Hrrrmph … you do know that I don*t want to spend three weeks on this, do you ? ;)

**Comment by TheFGFSEagle** [comment]
Alright, how do you like this ?
c182s-cover-pogress

**Comment by hbeni** [comment]
Looks great so far!

**Comment by TheFGFSEagle** [comment]
So you want me to extend it to the tail and wings, right ?

**Comment by hbeni** [comment]
Yes, like on the pucture i posted above

**Comment by wlbragg** [comment]
@TheFGFSEagle 

>if it's not already there I guess I could do the same for the 172 if wanted.

I think I will be able to use this same cover for the 172, even if I have to adjust it. We've been able to transfer much of each of these aircraft systems and products to each other. But thanks for the offer.

But I am currently working on the [Cub/SuperCub](https://github.com/wlbragg/J3Cub/tree/master) and I think eventually I would like to have a cover for it. I'm not sure if I want this much covering though. I'd have to do a little research to determine how much covering I want. For sure the flight surfaces and insulated cowling cover.

**Comment by hbeni** [comment]
@TheFGFSEagle Hi Eagle, how is it going?

**Comment by TheFGFSEagle** [comment]
No progress lately … sorry ! But on the other hand there isn't much left to do actually, if I can get an hour of free time I'd get it done … so maybe I'll finish it soon ! ;)

**Comment by TheFGFSEagle** [comment]
Got the horizontal stabilizer part finished today.

**Comment by TheFGFSEagle** [comment]
I think I'm done ! :)

**Comment by TheFGFSEagle** [comment]
I think I'm done ! :)
c182s-cover-pogress

**Comment by hbeni** [comment]
Thank you very much, will gute it a look shortly :)

**Comment by TheFGFSEagle** [comment]
I guess that could be done - although I do not really know how the ice / snow shader even works right now, so I'll let you do that ! :)

**Comment by hbeni** [comment]
Hey @TheFGFSEagle, how are you doing with the cover? My plane freezes already and desperately wants its winter coat :)

**Comment by TheFGFSEagle** [comment]
no progress yet, but I'll add the wing straps soon,

**Comment by hbeni** [comment]
Happy new year @TheFGFSEagle, I would be happy with the cover without straps, and you can finish them some other time?
Would love to finish this and get it out to the people :)

**Comment by TheFGFSEagle** [comment]
Happy new year benih - will finish it soon ! :)

**Comment by TheFGFSEagle** [comment]
Didn't find the time to finish it yet, so committed and pushed what I got so far to my repo branch `addPlaneCover`.

**Comment by hbeni** [comment]
Thanks, Eagle :) Thats great!

What material animation do you mean (sorry, those material and effects things still confuse me)?

**Comment by TheFGFSEagle** [comment]
The one for the livery (so that you can change the cover texture along with the other textures through the livery system)

Models/Exterior/cover/cover.xml lines 13-18

**Comment by hbeni** [comment]
I'll try to integrate that.
Just watched in the sim, looks nice already :)

**Comment by hbeni** [comment]
Integrated the work in branch `addPlaneCover-merged`.

@TheFGFSEagle 
One thing which is not working is changing cover texture with the livery.
I made the "blank" livery use the new "cover-grey.png" texture, but it stays red all the time...
What am i doing wrong?

**Comment by hbeni** [comment]
(reintegrated and force-pushed `addPlaneCover` branch)

**Comment by hbeni** [comment]
@TheFGFSEagle OK; changing the prop to just the image name works somewhat; but still the color is off widely. Blue gets almost black (with a prominent red hue).

Should be Grey:
grafik

Should be Blue:
grafik

Looks OK:
grafik

**Comment by TheFGFSEagle** [comment]
Ah, that's because I don't have the texture assigned in Blender and have a solid color there instead - the AC3D exporter sets the ambient color accordingly, which is what the red hue comes from - will fix.

**Comment by TheFGFSEagle** [comment]
Shouldn't `cover_blue.png`, `cover_grey.png`, etc. go into `Models/Liveries/`, then provide the path just like with the normal texture ? This should work with my latest commit.

**Comment by TheFGFSEagle** [comment]
Did it myself, textures should be loading correctly now - will correct the red hue later.

**Comment by TheFGFSEagle** [comment]
Red hue removed.

**Comment by hbeni** [comment]
Thanks, looks good!

One final thing, I don't understand tough:
- in the `cover/` folder, we have a `cover.png`. Why don't we reference the  `default-cover.png` in the Liverys folder?
- The `default-cover.png`
  - is not referenced anywhere. Why is it there?
  - And it should be named cover_default.png imho, to stay consistent with the others.

**Comment by hbeni** [comment]
and what is the reason you switched the `pick` animation with `knob`?
I would prefer that the user actually has to click the cover instead of accidentally removing it with the mouse wheel :)

**Comment by TheFGFSEagle** [comment]
> Why don't we reference the default-cover.png in the Liverys folder?

Having the AC3D file reference a texture anywhere else than in the same directory is prone to breaking when the texture is moved / renamed, and in fact the Blender AC exporter doesn't even let you do that - it will copy the texture into the folder the AC file is exported to.

**Comment by TheFGFSEagle** [comment]
> The default-cover.png is not referenced anywhere. Why is it there?

It was referenced at first but you replaced those references with those to the `cover_blue.png` etc. files - feel free to remove it ! :)

**Comment by TheFGFSEagle** [comment]
> and what is the reason you switched the pick animation with knob ? I would prefer that the user actually has to click the cover instead of accidentally removing it with the mouse wheel :)

Because pick is deprecared: https://wiki.flightgear.org/Howto:Make_a_clickable_panel#Pick

> As of FlightGear 2.11 (Git version), there's a new [Knob / slider animation](https://wiki.flightgear.org/Knob_/_slider_animation), to be used instead of the pick animation.

But removing the cover with the scroll wheel really isn't great either … we'd need a `click` animation that behaves just like the `knob` / `pick` animation but reacts to clicks only (or rather, add an option to the `knob` animation to ignore scrolling).

**Comment by TheFGFSEagle** [comment]
Try this:
```patch
diff --git a/simgear/scene/model/SGPickAnimation.cxx b/simgear/scene/model/SGPickAnimation.cxx
index ad4b28d3..153de617 100644
--- a/simgear/scene/model/SGPickAnimation.cxx
+++ b/simgear/scene/model/SGPickAnimation.cxx
@@ -665,6 +665,10 @@ public:
             _cursorName = "drag-horizontal";
           }
         }
+        
+        if (configNode->hasChild("ignore-scrolling")) {
+            _ignoreScrolling = configNode->getBoolValue("ignore-scrolling");
+        }
     }
 
     bool buttonPressed( int button, const osgGA::GUIEventAdapter& ea, const Info& ) override
@@ -680,10 +684,10 @@ public:
             const int decreaseMouseWheel = static_knobMouseWheelAlternateDirection ? 3 : 4;
 
             _direction = DIRECTION_NONE;
-            if ((button == 0) || (button == increaseMouseWheel)) {
+            if ((button == 0) || (button == increaseMouseWheel && !_ignoreScrolling)) {
                 _direction = DIRECTION_INCREASE;
             }
-            else if ((button == 1) || (button == decreaseMouseWheel)) {
+            else if ((button == 1) || (button == decreaseMouseWheel && !_ignoreScrolling)) {
                 _direction = DIRECTION_DECREASE;
             }
             else {
@@ -844,6 +848,7 @@ private:
     double _dragScale;
   
     std::string _cursorName;
+    bool _ignoreScrolling;
 };
 
 ///////////////////////////////////////////////////////////////////////////////
```
then add `<ignore-scrolling type="bool">true</ignore-scrolling>` to the `knob` animation in cover.xml.

**Comment by hbeni** [comment]
> Because pick is deprecared:

I think its not. Knob is just a better and more flexible option in most cases. But not in our case here.

so thanks for clarifying, i think i can go and finally integrate that now :)

i tried to do the frosting effect to the cover, but this effect stuff needs to wait more.
I cant get warm with it so i leave it for future endeavours

**Comment by hbeni** [comment]
Will do :)

**Comment by TheFGFSEagle** [comment]
Thanks ! :)

**Comment by hbeni** [comment]
> diff --git a/simgear/scene/model/SGPickAnimation.cxx b/simgear/scene/model/SGPickAnimation.cxx

Your patch and config adjustment seems to do what it should :)

But, I'm courious what James will say; the same can be achieved without the patch by just disabling the binds of all the buttons in the `knob`-animation.
Or by just using `pick`...

But otoh, more options are good, in my view.

**Comment by TheFGFSEagle** [comment]
> by just disabling the binds of all the buttons in the knob-animation.
How would you do this ?

**Comment by hbeni** [comment]
I think by defining explicit `<bindings>` for the actions. Like described in the article.
But never done that. I have chosen `pick` whenever it needs to be simple.

**Comment by TheFGFSEagle** [comment]
Uh, James definitely does not want another parameter for the knob / slider animation because it already has many - if at all it would be a new "click" animation !

**Comment by TheFGFSEagle** [comment]
but then. maybe it's not worth it.

**Pull request merged**
