### PR TITLE
Fix #337: Apply chocks only when their state differ 

### LINKED ISSUE #337: Got stuck in chocks
Today while testing i got an interesting behavior (FGFS 2020.3.0).
I did secure the plane after the last session and restored its state while starting using the overlay "cold&dark" state.
Testing showed the problem also occurs when applying "auto" state.

That resultet in:
- the aircraft securing dialog was showing chocks disabled
- chocks beeing on the ground, leaving me with an unrollable plane
- trying to add/remove chocks trough the GUI resulted in adding additional chocks. The original ones could not be removed.

### PR DESCRIPTION
**Pull request by hbeni**
(fixes getting stuck with overlay cold&dark)

### CODE REVIEW

**Comment by hbeni** [comment]
Tested it, should be good for merge

**Comment by HHS81** [comment]
Hmm... maybe the symptoms are solved. But not the cause. I experienced something often while develoing this feature. Reason alsways had been somewhere in the gui dialogs. I check again

**Comment by HHS81** [comment]
Indeed, interesting. Only appears with cold and dark state pre-selection. Merged.

**Comment by hbeni** [comment]
I think the actual problem was that the state nasal code always set the chocks property, and the listener to that adds a new model.
The fix was that the property is only changed if the value differs.

**Comment by HHS81** [comment]
@hbeni yea, nice catch!

**Pull request merged**
