### PR TITLE
Issue525 save dg offset (by switching instrument to <heading-indicator-dg>)

### PR DESCRIPTION
**Pull request by hbeni**
This switches the heading indicator to the `heading-indicator-dg` implementation which is more powerful and realistic.

:warning: PR is based on switching to the DG based heading indicator, and only works with the patch to the core:
https://sourceforge.net/p/flightgear/codetickets/2839/

:information_source: Regarding the movement-errors, there is discussion on the mailing list if this is realistic:  https://sourceforge.net/p/flightgear/mailman/flightgear-devel/thread/6e66f08e3fb3f02a9d5c557cfd7a2910%40hallinger.org/#msg53245268
My impression is, that there should be no permanent movement related errors, as the gyro should move relatively freely due to the two axis bearing.

regarding to the videos:
- Uncaged maneuver limits are (for air driven): +-55° in pitch or roll (two videos below say this). IMHO the current c++ coded limits are too rigid. And also it would be nice to have a caging feature.
- Mechanical limits prevent completely freely movement.

----
- [x] Switch to new DG
- [x] error value: only let this apply when the limits (55° pitch/bank) are exceeded
- :warning: _Before merge_;
  - [x] Wait for SF ticket [2839](https://sourceforge.net/p/flightgear/codetickets/2839/) being merged to FGFS/next (so `<suction>` is a supported source of the instrument)
  - [x] Watch SF ticket [2840](https://sourceforge.net/p/flightgear/codetickets/2840/) regarding error discussion (Maybe the filter clamping the error prop can be removed)

----

Refs:
- https://www.youtube.com/watch?v=hVsx4XWafXg Gyroscopic Instruments
- https://m.youtube.com/watch?v=9EZ9ZI8kAWM Operation And Errors Of Directional Gyro Indicator | Lecture 27
- https://www.youtube.com/watch?v=q1TVR9xdl64 The Heading Indicator (Directional Gyro)
- Mailing list discussion: https://sourceforge.net/p/flightgear/mailman/flightgear-devel/thread/6e66f08e3fb3f02a9d5c557cfd7a2910%40hallinger.org/#msg53245268
- FGFS Wiki Newsletter Jan/2024: https://wiki.flightgear.org/FlightGear_Newsletter_January_2024#Gyro_based_instruments_enhancements (with more info)
- C172 sister ticket: https://github.com/c172p-team/c172p/pull/1490

### CODE REVIEW

**Comment by hbeni** [comment]
Test flight ILS outbound track, turnaround and re-interception worked good as expected.

**Comment by hbeni** [comment]
Opened a related, but not neccesarily connected ticket at SF: https://sourceforge.net/p/flightgear/codetickets/2840/
About the error code.

**Comment by hbeni** [comment]
Error is now only applied when bank/pitch is off limits.

Now lets wait for the discussion regarding the core changes...

**Comment by hbeni** [comment]
3da1902a39d6b595947ed5f37cc3ff78185bc471 needs verification in the following regards:
- VSI damper at sim start and ground working?
- DG limits enforcer limits error accumulation to excess of 55° pitch/bank
- Autostart instrument calibration still working
- gyro auto-spinup for calibration working

**Comment by hbeni** [comment]
Just had a test flight in the GA Wednesday group and it looks good.

**Comment by hbeni** [comment]
I really think this is ready to be merged once the [Core-Ticket](https://sourceforge.net/p/flightgear/codetickets/2839/) is merged.

**Comment by hbeni** [comment]
So, https://sourceforge.net/p/flightgear/codetickets/2839/ was merged (a small but remains) and this PR can finally be merged :)

I will watch this for some days, do some test flights to see if something unusual crept in, and then merge.
For merge, I think I want to clean up the git history a bit.

**Comment by hbeni** [comment]
Need to recheck g-force.
Spin should not put the gyro into tumbling mode.

http://www.youtube.com/watch?v=OiKcG7NOdUk

**Comment by TheFGFSEagle** [comment]
Can someone tell me why I get ghost notifications for this pull request almost every day ?

**Comment by hbeni** [comment]
> Can someone tell me why I get ghost notifications for this pull request almost every day ?

No idea
Maybe hit „unsubscribe“?

**Comment by hbeni** [comment]
> So, https://sourceforge.net/p/flightgear/codetickets/2839/ was merged (a small but remains) and this PR can finally be merged :)
> 
> I will watch this for some days, do some test flights to see if something unusual crept in, and then merge. For merge, I think I want to clean up the git history a bit.

There is still stuff ongoing in the core (see the linked ticket); the HI will swap when passing N/S, still beeing investigated.

**Comment by hbeni** [comment]
Looks like the fgfs code issue was resolved.

Testing needed to verify, then we can merge

**Comment by hbeni** [comment]
Tested, looks good.

**Comment by hbeni** [comment]
GA Wednesday IFR flight in nearly to hours did not show strange things.

**Pull request merged**
