### PR TITLE
Revise NAV needle deflections

### LINKED ISSUE #522: Revise NAV1/NAV2 needle deflection values
The CDI should represent 2° off per dot, this is slightly off currently.

The VOR gauges currently just scale the deflection using a fixed factor, and that is off somewhat.
Full deflection (=10°) should give 5 dots.

- [x] NAV1
- [x] NAV2

----
Ref:
- Manual https://www.manualslib.com/products/Honeywell-Ki-209-8777567.html
-  Wiki https://en.wikipedia.org/wiki/Course_deviation_indicator

### PR DESCRIPTION
**Pull request by hbeni**
Fix #522

### CODE REVIEW

**Comment by hbeni** [comment]
Tested and ready for merge, imho

**Comment by wlbragg** [comment]
@hbeni do you know if this applies to c172p?

**Comment by hbeni** [comment]
No, but its easy to check; just temporarily link the needle to a test prop which you can adjust using the prop browser.

Each dot should represent 2degrees using a VOR (tune to that, ILS is more sensitive but will automatically match if the VOR/2deg is correct)

**Comment by wlbragg** [comment]
OK, thanks.

**Comment by hbeni** [comment]
Just briefly checked:
- NAV1 is good on the right, and slightly off to the left
- NAV2 is off on both sides

**Pull request merged**
