### PR TITLE
Issue 151

### PR DESCRIPTION
**Pull request by HHS81**
This PR add fuel pump sound. When engaged you hear the looped sound, when switched off pump-end.wav will sound.
Fix Issue #151

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@HHS81 Ok, so I tested this and here are my comments:

- the fuel pump sound implementation works great, thanks!
- when I load the sim, I can already hear the gyro sound, likely because the avionics and master switches are all on (by the way, I can't see any option to start the aircraft in cold and dark conditions, we should add one). After turning off those switches, the gyro sound takes ages to die off. I assume this is a feature, so can you just confirm this is intentional? If so, all good.
- at low throttle, the gyro sound is easily cutting through the sound of the engine. I don't think the issue is with the gyro sound but rather with the engine sound: perhaps the volume at low throttle should not be that soft.

**Comment by HHS81** [comment]
@gilbertohasnofb 
> After turning off those switches, the gyro sound takes ages to die off. I assume this is a feature, so can you just confirm this is intentional? If so, all good.

Yes, the spinning of the gyro is hardcoded and seems realistic to me. So yes, it needs a while until the spin has stopped.

> at low throttle, the gyro sound is easily cutting through the sound of the engine. I don't think the issue is with the gyro sound but rather with the engine sound: perhaps the volume at low throttle should not be that soft.

I'm not sure which of the instruments makes noise in reality. According [this source](http://www.pprune.org/private-flying/426458-turn-coordinator-gyro.html) it does. So I aligned to every instruments, which has <spin>-tag the gyro sound. 
I can set the volume of the gyro down, and increase engine volume with low throttle

**Comment by gilbertohasnofb** [comment]
> I can set the volume of the gyro down, and increase engine volume with low throttle

Perhaps that would be a good solution, and then we merge this. Everything else is looking good then!

I will also open a new issue for the cold and dark option.

**Comment by HHS81** [comment]
@gilbertohasnofb 
O.k., only the Turn-indicator uses an electrical gyro according POH, So I removed the other ones from the sound.xml.

The interesting finding: our FGFS heading-indicator is electrically driven. But it should be vacuum driven according POH. I wonder where to change it.

Anyway, please test it!

**Comment by gilbertohasnofb** [comment]
> O.k., only the Turn-indicator uses an electrical gyro according POH, So I removed the other ones from the sound.xml.

Sounds good to me, I will test now.

> The interesting finding: our FGFS heading-indicator is electrically driven. But it should be vacuum driven according POH. I wonder where to change it.

Will you open a new issue about it so we don't forget it? I did open one for the startup state options.

**Comment by hbeni** [comment]
this is already fixed #151

**Pull request merged**
