### PR TITLE
Simple damage system

### PR DESCRIPTION
**Pull request by hbeni**
Implemented a simple damage detection System (as foundation to #141):
- [x] Basic system ported over from c172p and adjusted coefficients accordingly to already present values (`Systems/damage.xml`)
- [x] Added a simple damage handler (`Nasal/damage.nas`) that informs the pilot via text of broken things.
  Now we could practice smooth landings without killing the front gear :)
- [x] Added a simple gui to aircraft dialog showing all damaged parts, so pilot can check it.
- [x] Damage should be stored over sessions when initializing "saved" state. This should be an easy one, just had no time to test this yet.
- [x] It has <s>no</s> effect on flight dynamics <s>yet. This could easily achieved by integrating the damage values to the fcs calculations, </s>like it's done in the c172p
- [x] gear should collapse; again this could be made easily by adjusting the z-pos of the contact points

As said in #141, model/graphical stuff etc. is to be done separately; Heiko already has some ideas for that.

- [x] Port that over to the C182T
- [x] when wings break, fuel should be leaked and the sensor break: small damage should make a leak, fully broken should set fuel to 0 and fail the sensor.

### CODE REVIEW

**Comment by HHS81** [comment]
@hbeni 
Sorry, I`m busy with real life stuff- no corona holidays for me.

So, you are now going the c172p way? I wasn`t happy with this, since I experience a significiant lower fps with the c172p compared with the c182s. 
Otherwise using the z-values of the contact points as suggested by you as damage indication (strength, affected systems) seems cheap.

**Comment by hbeni** [comment]
Hi Heiko, i had the FPS in mind and that was the reason i implemented it using jsbsim, which should be quit fast. Its really just some really small calculations this far.
Also i really wanted to train my landings :)

I think the hiccups you experienced came from the effects with the 3d stuff. I could not trace performance issues here so far; do you have any now with the branch?

Also, this was not soooo much of work so far, so if you have a better way and time to implement it, we can just easily throw away this implementation. Most of it is in `damage.xml`.

**Comment by stuartbuchanan** [comment]
Like Heiko, I'm not a huge fan of the c172p approach to adding very complex systems to what are fundamentally edge-cases and trying to model the impact of damage..

I think it's very good to notify the user when limits are exceeded that would damage the aircraft - wing G-loading, excess undercarriage loads, exceeding VNE.

However I'm less convinced about trying to _model_ that damage either graphically or in the FDM.  In my mind it is sufficient to simply provide a warning message to the screen.  Some users will ignore this, others will be trying to fly within the envelope.

In terms of damage modeling itself:
- Under excess loads, undercarriage on GA aircraft (microlights) tends to fail completely - the aircraft basically stops moving on the ground with a bent leg.  So there's little point in trying to model the effects of this - the aircraft simply cannot move under it's own power.

I also don't think modeling damage to aircraft after they exceed Vne is accurate.  As part of my annual check flight, my aircraft is flown as close to Vne as it can (e.g. steep dive, full power).  So I do not think it would be damaged as soon as it exceeds it in any real way.  

-Stuart

**Comment by hbeni** [comment]
The problem is to detect that some value was exceeded. This is the part which was modelled in jsbsim, because it is simple and fast there.
Currently there is a text expression in red when this happens.

I agree that we really don't need some fancy 3D modelling of damage for now (however that would add the public value of the simulator in my eyes), but i think it is very useful that the plane will not be flyable anymore when the wings broke (they don't do it straight out and well above the Vne value currently), as well as a collapsed gear - it gives immediate visual feedback to the pilot.

**Comment by hbeni** [comment]
No worries. I donÄt think it is done in stone, but i think what we have here is better than nothing. We may come back and improve anytime.

**Comment by hbeni** [comment]
@HHS81 
> I like the way X-Plane handles it.

I don't know XPlane - how does it handle it?

**Comment by HHS81** [comment]
@hbeni 
As I could see, similar now like you now implemented. They feature overspeed of flaps, tyre damage, and engine damage on harder landings. 
I will add some animations to the landing gears and see how I get the friction coefficient manipulated when gear is bent.

**Comment by hbeni** [comment]
Animations would be nice but please stay sharp on performance...
I think the performance got in the 172 comes from switching the 3d models.

**Comment by wlbragg** [comment]
>I think the performance got in the 172 comes from switching the 3d models.

That is right. It's almost entirely the extra mesh. The j3 was even worse as it had unnecessary 4kX4k textures. I think had I to do it all over from scratch, I would use shaders for the damage visuals. Something akin to wingflex.
As far as to do or not to do at all and peoples personal preferences. I think it is much more pleasing to see the results of messing up VS any message unless the message is "real time/real life" such as a stall warning siren or engine flame out. FDM  changes due to structural failures if done with much planning could really enhance the simulation for emergency landing training and the likes. I think visualizing gear damage or collapse should be fundamental to a good simulation. It was even crudely built into the core. The approach I took was before I had gained much experience with modeling or FDM components and could be vastly improved on. But I feel it is most certainly value added to the simulation in general.
But then again I also believe we should finish the ground cover effects on the wheels and gears in the core code. All of these things were obviously at least thought about originally, or we wouldn't have some of the structure supporting these things, like ground cover hardness and friction values.
All the code I added for the ground effects (sinking and friction) had little noticeable impact on performance. But it made the gear change outs useful for something other than esthetics. Now the bush gears work on terrain where the stock gear doesn't and the skies work on snow where the default and bush gear don't. I personally like having that ability and realism.

**Comment by HHS81** [comment]
No fps impact noticed so far- but only prop and gear done yet.

crashed

**Comment by hbeni** [comment]
Looks very good!
(Poor plane 😢)

**Comment by wlbragg** [comment]
Looks good, if your into seeing your prop mangled, ha!

>That is right. It's almost entirely the extra mesh. The j3 was even worse as it had unnecessary 4kX4k textures. 

Now that I think about it, the first version of damage on the c172p was "more" expensive than the current version. The entire wing unit was one piece and required several duplicated of the entire wing bent in the different damage patterns. a set for left wing damage, right wing damage and both wings damage.
Similar to how the j3 still is. On top of this extra mesh were 4k textures.
cubdamage

I need to change the j3 to what we did to the c172p. 
c172pdamage

**Comment by hbeni** [comment]
@HHS81 Heiko, what do you think: The damage inspection GUI was introduced from me because i had the impression, damage will not be reflected in the model in the near timeframe.
With your work, i think it's obsolete and can be removed (at least when the wings are bent) :)

**Comment by wlbragg** [comment]
FYI: I noticed you may be using a "repairing" flag to use for settling damage when resetting damage, similar to what the c172p does. Note an unresolved issue with the repairing flag and timer on "Airport Relocation" using the GUI.
See https://github.com/c172p-team/c172p/issues/1325

**Comment by hbeni** [comment]
> FYI: I noticed you may be using a "repairing" flag to use for settling damage when resetting damage, similar to what the c172p does. Note an unresolved issue with the repairing flag and timer on "Airport Relocation" using the GUI.
> See [c172p-team/c172p#1325](https://github.com/c172p-team/c172p/issues/1325)

Thanks for the heads up! i was not able to reproduce that with the c182s on this branch.

**Comment by hbeni** [comment]
Oh god, it worked. Poor plane... Good that its so cheap to repair :)
I'm really thrilled how you will implement the broken wings 3D representation.

**Comment by HHS81** [comment]
> 
> 
> Nice, it never occurred to me to do that. Good idea!

I didn`t like the fact that you can fly through trees of a forest and still get up into the air. I don´t want to have a crash simulator, but also not an arcade game, where you get signalized "game over".
Especially in Nort America with all those little airports hidden in the woods, the perfect place for a C182.

**Comment by HHS81** [comment]
> 
> 
@hbeni 
> Oh god, it worked. Poor plane... Good that its so cheap to repair :)
> I'm really thrilled how you will implement the broken wings 3D representation.

First I want to find out, why the JSBsim structure points don´t recognize WOW. Then I will see...

**Comment by hbeni** [comment]
Hey Heiko,

> First I want to find out, why the JSBsim structure points don´t recognize WOW. 


i tried to figure out what exactly you are after, can you elaborate a bit so i can assist?

**Comment by stuartbuchanan** [comment]
Damage < 90ft AGL assumes that all trees are that high.

Looking through the regional material definitions, there are a lot of areas
where the height of trees is significantly lower than 90ft:

Here's a very rough distribution of heights:
10: 14
15: 24
20: 73
25: 63
30: 0

Obviously that is a count of regions, not the areas of the said regions.

I suggest lowering the limit to (say) 50ft (~15m).  That would ensure you
are hitting the tree below the tree-tops (we generate some variation in the
tree-top height as well), account for the c182 being high-wing, and the
wing being strong enough to work as a leaf-strimmer for small branches!

(Personally, I'm not a fan of complicated damage systems, and particularly
the effort to animate a crashed aircraft.  My experience IRL is that no-one
wants to look at a crashed aircraft except the accident investigator and
the engineer fixing it.)

-Stuart

**Comment by hbeni** [comment]
Would it be possible to get the current regions average tree height (or even the tree height from the actual area) from the property tree? If so, we could easily make it dynamically.

**Comment by HHS81** [comment]
> 
> 
> Would it be possible to get the current regions average tree height (or even the tree height from the actual area) from the property tree? If so, we could easily make it dynamically.

Unfortunately not. They are not shown in the property tree, otherwise I would like have done it that way. 😞

**Comment by hbeni** [comment]
Should we open a FR ticket on fgfs core to get the property? :)

**Comment by HHS81** [comment]
@stuartbuchanan 
> 
> Damage < 90ft AGL assumes that all trees are that high. Looking through the regional material definitions, there are a lot of areas where the height of trees is significantly lower than 90ft: Here's a very rough distribution of heights: 10: 14 15: 24 20: 73 25: 63 30: 0 Obviously that is a count of regions, not the areas of the said regions. I suggest lowering the limit to (say) 50ft (~15m). That would ensure you are hitting the tree below the tree-tops (we generate some variation in the tree-top height as well), account for the c182 being high-wing, and the wing being strong enough to work as a leaf-strimmer for small branches! (Personally, I'm not a fan of complicated damage systems, and particularly the effort to animate a crashed aircraft. My experience IRL is that no-one wants to look at a crashed aircraft except the accident investigator and the engineer fixing it.)
> […](#)
> -Stuart

Yes, that sounds like a good compromise. 
I don`t want to have crash simulator as well. On the othe side, we claim to be a simulator and not an arcade game with "game over". But I would like to have an effect when as an example exceeding rwys - flying through the trees is too simple. I don`t want to go further, because I think it is enough for the user to hear the bang hitting the trees and loosing altittude with ending sitting on the ground. It shows people that the ability of the aircraft is limited.

**Comment by HHS81** [comment]
> 
> 
> Should we open a FR ticket on fgfs core to get the property? :)

You can do it if you want

**Comment by HHS81** [comment]
> 
> 
> Hey Heiko,
> 
> > First I want to find out, why the JSBsim structure points don´t recognize WOW.
> 
> i tried to figure out what exactly you are after, can you elaborate a bit so i can assist?

I don´t get any WOW-signal of the structure points, when the gear is crashed

**Comment by hbeni** [comment]
> > Should we open a FR ticket on fgfs core to get the property? :)
> 
> You can do it if you want

done: https://sourceforge.net/p/flightgear/codetickets/2389/

**Comment by hbeni** [comment]
> Yes, that sounds like a good compromise.

I think that too. The crash-feedback is extremely valuable tough, especially with the gear collapse we can train good landings.

**Comment by hbeni** [comment]
@HHS81 I tried it and can't reproduce (ie i get WOW contacts after crash) - is it this what you where looking after?

Screenshot_20201027_090139

**Comment by hbeni** [comment]
So, i just ported missing bits to the C182T :)

@HHS81 Heiko, did my investigation above (https://github.com/HHS81/c182s/pull/328#issuecomment-717063039) help you already?

**Comment by hbeni** [comment]
I just added a small enhancement: If the wings are damaged, fuel will leak out of the broken tank.
If the wing damage is severe (like ripping it off or collide with something), the whole fuel will be leaked instantly, and navlights/strobe will cease to work.

I think, the last thing missing here is the model showing the wing damage. the other stuff seems to work fine, both on the S and the T variant; i did plenty of test flights already.

**Comment by HHS81** [comment]
> 
> 
> I just added a small enhancement: If the wings are damaged, fuel will leak out of the broken tank.
> If the wing damage is severe (like ripping it off or collide with something), the whole fuel will be leaked instantly, and navlights/strobe will cease to work.
> 
> I think, the last thing missing here is the model showing the wing damage. the other stuff seems to work fine, both on the S and the T variant; i did plenty of test flights already.

Hmm... the Cessna 182s has fuel bladders- I don`t think that fuel will leak with low wing damage.

**Comment by hbeni** [comment]
> Hmm... the Cessna 182s has fuel bladders- I don`t think that fuel will leak with low wing damage.

Thanks for catching, i didn't know. The POH id not mention specifics :)
I fixed that.

Did my https://github.com/HHS81/c182s/pull/328#issuecomment-717063039 help you?

**Comment by HHS81** [comment]
> 

> Did my [#328 (comment)](https://github.com/HHS81/c182s/pull/328#issuecomment-717063039) help you?

Not really- but I guess I do know why it behaves like that. I think we can merge

**Comment by hbeni** [comment]
> I think we can merge

@HHS81 should i, or do you want to do it yourself?

**Pull request merged**
