### PR TITLE
Add turn-indicator inop flag

### PR DESCRIPTION
**Pull request by hbeni**
Quick lunch break start:

grafik grafik
grafik grafik

### CODE REVIEW

**Comment by hbeni** [comment]
While testing i found a minor problem in the elec system.
The electric instruments should be wired to the ignition switch, and that should only output power when the INST-Breaker is in _and_ the key is turned away from `off`.

grafik

Will fix that later in this branch.

**Comment by hbeni** [comment]
OK turned out, it's ok already:
grafik

@HHS81 so i will merge - if you agree?

**Comment by HHS81** [comment]
Nice work!

**Comment by HHS81** [comment]
I´ll merge it, as there will be another important fix come from me after that

**Pull request merged**
