### PR TITLE
Issue #252: add propwash effect by dany93

### PR DESCRIPTION
**Pull request by HHS81**
This PR adds the propwash effect by dany93.
This means at full power and low speed you will need a signifficient amount of right rudder to keep the aircraft straight.

### CODE REVIEW

**Comment by HHS81** [comment]
has anyone tested it?

**Comment by hbeni** [comment]
no...

**Comment by hbeni** [comment]
ok, now; what a strong effect :)
It makes starting really a challenge, especially without rudder pedals.
If i am allowed to propose, i think it would be advisable to make this realism grade user toggable in the aircraft menu.

**Comment by HHS81** [comment]
Hmm, I thought this as well.
But the c172p has this enabled per default, and X-Plane of course as well.
And since the C182S is something more complex (IFR, constant speed prop, faster) I think that would be o.k.

**Comment by hbeni** [comment]
okay then!
However i also cant tell if the effect is realistic; but lets assume this for now.

**Comment by HHS81** [comment]
waiting to be merged

**Pull request merged**
