### PR TITLE
Issue 142

### PR DESCRIPTION
**Pull request by HHS81**
Correct length of Throttle, Prop and mixture control lever rods; remove ambient occlusion from Throttle, Prop and Mixture control rods to get the actual color

### CODE REVIEW

**Comment by HHS81** [comment]
@gilbertohasnofb @hbeni  Ping

**Comment by gilbertohasnofb** [comment]
@HHS81 something's wrong, at least on my side:

fgfs-screen-001

No errors on log or what-so-ever, any ideas?

**Comment by HHS81** [comment]
Oh. Yes,  I know how it happened. Will fix it until tuesday.

**Comment by gilbertohasnofb** [comment]
No rush, once you push a fix I will be happy to test and merge it. Thanks!

**Comment by hbeni** [comment]
Just so i can learn something, what is causing the problem?

**Comment by HHS81** [comment]
Should be o.k. now:

fgfs-screen-001

**Comment by gilbertohasnofb** [comment]
@hbeni I think it was just a matter of applying textures to the model.

@HHS81 the textures are back, but I noticed another problem: the mixture lever going too much forwards and is "entering" the panel when fully rich, see green arrows below. Also, the texture around the metallic end of the throttle lever looks a bit weird (see pink arrow), why are there those black lines at each corner? Is the texture perhaps not properly applied? I looked at the png and they look fine.

fgfs-screen-001

**Comment by HHS81** [comment]
I will have take look the next days. It is already late here.

**Comment by gilbertohasnofb** [comment]
No rush.

**Comment by HHS81** [comment]
@gilbertohasnofb 
I corrected the uvmap of the throttle base - it was a "bit out of shape". I also now corrected the travel way of the mixture lever and of the throttle (which somehow denied my local changes before)
Is now ready to  merge!

**Comment by gilbertohasnofb** [comment]
@HHS81 all looking good now, thanks for the fix!

**Pull request merged**
