### PR TITLE
Fix various minor instrument bugs

### LINKED ISSUE #393: NAV/VOR gauge misses yellow tick marks
The NAV/VOR gauges should have little yellow triangles at the 12 and 6 position as reference for the OBS rotation:

grafik

### LINKED ISSUE #394: ADF gauge markings should be red
grafik

The markings are here, but white

### LINKED ISSUE #395: Some instruments knobs lighting is not correct
- [x] The knobs of AI and altimeter appear way too black;
- [x] also the artifical horizont cage knob sits ion a black rectangle.

grafik

### PR DESCRIPTION
**Pull request by hbeni**
- [x] Fix #393
- [x] Fix #394 
- [x] Fix #395

### CODE REVIEW

**Comment by hbeni** [comment]
New Nav gauges:
grafik

**Comment by hbeni** [comment]
Note to myself: move the ticks to vor05.png if that is transparent, in order to get them more to the foreground

**Comment by hbeni** [comment]
ADF gauge with refined Aircraft symbol:
grafik

**Comment by hbeni** [comment]
Done, final result:
grafik

**Comment by hbeni** [comment]
Done, final result:
grafik

**Comment by hbeni** [comment]
Heiko, please merge this if you like it :)

**Comment by HHS81** [comment]
Done! 😃

**Pull request merged**
