### PR TITLE
New Livery: G-XLTG

### PR DESCRIPTION
**Pull request by HHS81**
Signed-off-by: hhs81 <heiko.h.schulz@gmx.net>

### CODE REVIEW

**Comment by hbeni** [comment]
Nice one!

💡 just an idea: the new canvas Registration allows for changing fonts and colours - we may leverage that to allow for example this livery (and the default one, etc) to have dynamic Registration.
What do you think about that?

@HHS81

**Comment by HHS81** [comment]
@hbeni 
> 
> 
> Nice one!
> 
> 💡 just an idea: the new canvas Registration allows for changing fonts and colours - we may leverage that to allow for example this livery (and the default one, etc) to have dynamic Registration.
> What do you think about that?
> 
> @HHS81

This livery is based on a real livery (https://abpic.co.uk/pictures/registration/G-XLTG). There aren`t so much interesting liveries for Cessna 182S (the T-variant has more, and the older ones anyway). So for real based liveries I woulnd`t like to see dynamic registrations.
But I may produce some Retro-style liveries, where we could use this.

**Comment by hbeni** [comment]
Yes, and the boring-grey default Liberty with c182 as Registration may also be dynamic (with c182 as default?)

**Comment by HHS81** [comment]
Yep, that would be the first candiate! 👍

**Pull request merged**
