### PR TITLE
Retexturing EGT/CHT

### LINKED ISSUE #39: Model the correct ELT-model
Model the correct ELT-model used by Cessna in their 182 S Skylane according to POH.

### PR DESCRIPTION
**Pull request by hbeni**
New EGT/CHT Texture (fix #39)

Did the textures, see branch [`Issue39-EGT-CHT`](https://github.com/HHS81/c182s/tree/Issue39-EGT-CHT) (and EGT branch in textures repo)

<s>Still missing is the knob (my blender crashes when loading the `.ac`):</s>
- [x] I added a texture part for the knob already (lower left corner).
- [x] so its just the UVmap that needs an update.
- [x] Maybe the knob should be made a little bigger.
- [x] Also the REF needle should be yellow.

grafik

### CODE REVIEW

**Comment by HHS81** [comment]
seems there different versions of the EGT out there: http://rentmy182.com/wp-content/grand-media/image/WLTF-Rent-My-182-14.jpg

**Comment by HHS81** [comment]
@hbeni otherwise yours looks nice and better than mine- I used the POH as default, and didn`t update the textures when I fiund better pictures.

**Comment by hbeni** [comment]
Do you want me to redo the red line at 500?
I would say it’s better/more clear.

**Comment by hbeni** [comment]
Also, do you think you have a little time for the 3D work? My blender seems to crash constantly...

**Comment by HHS81** [comment]
not this week unfortunately 😞

**Comment by hbeni** [comment]
Better :)
grafik

**Comment by hbeni** [comment]
Done:
grafik

**Pull request merged**
