### PR TITLE
Oil management

### PR DESCRIPTION
**Pull request by hbeni**
Fixing #125 with extended oil simulation depending on time the oil was in service (so simulating need for oil changes)

### CODE REVIEW

**Comment by HHS81** [comment]
@hbeni @gilbertohasnofb 
I didn't found time the last months, and the last weeks showed me that I can't work anymore late into night, since I have to get up early for job.

So it seems I missed a lot, and currently I'm looking through all files and check things. It will need some time today.

**Comment by hbeni** [comment]
Updated the liverys (see also PR at the texture repo)

**Comment by gilbertohasnofb** [comment]
> So it seems I missed a lot, and currently I'm looking through all files and check things. It will need some time today.

@HHS81 No rush. Just please don't miss my request to add @hbeni to the https://github.com/HHS81/c182-Textures repository, as he is now also working with textures.

**Comment by HHS81** [comment]
@hbeni Great contribution!

**Comment by HHS81** [comment]
@hbeni  
A nice method for oil viscosity controlled by temperature by Ron Jensen (jentron): [https://sourceforge.net/p/jsbsim/mailman/message/30264774/](https://sourceforge.net/p/jsbsim/mailman/message/30264774/)

**Comment by HHS81** [comment]
@hbeni so we wouldn't need a logic like engine-killed. Just a simple function, where oil-level >certain level leeds to a higher frction and with that to a high `propulsion/engine/friction-hp` which stops the engine, more realism. That's btw. how I will implement prop strike...

`

**Comment by hbeni** [comment]
Sounds good to enhance the sim with this sometime!
Can we get realistic numbers for jentrons "made up" numbers?

**Comment by hbeni** [comment]
Oh, and the engine-killed property (and logic) would still be needed for two other reasons:
1. To support engine killing if water was in the fuel tanks (fuel-contamination)
2. To be able to expose some API to promptly kill the engine from outside (tutorial-code, telnet, ...)

That said, simulating friction would be cool nonetheless.

**Pull request merged**
