### PR TITLE
#383: fix Issue 383 by changing foresign; made gears more springy, sy…

### PR DESCRIPTION
**Pull request by HHS81**
…ncronized c182t

Signed-off-by: hhs81 <heiko.h.schulz@gmx.net>

### CODE REVIEW

**Comment by HHS81** [comment]
@hbeni should work now

**Comment by hbeni** [comment]
will have a look!

**Comment by hbeni** [comment]
If it works, i will merge it into the kap branch; and not master, ok?

**Comment by hbeni** [comment]
merged into `newKAP140`

**Pull request closed without merging**
