### PR TITLE
Issue218

### PR DESCRIPTION
**Pull request by HHS81**
Fix of Issue#218: added WinterKit, animated it, fixed some material settings due to faulty Blender conversion, also fixed wrong selection of the spinner

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Stunning work, Heiko, looks great. Just please make sure that any modifications to textures are also synchronized with https://github.com/HHS81/c182-Textures/ so that no future modifications result in conflicts (e.g. winterization kit losing its textures)

**Comment by hbeni** [comment]
@HHS81 in the default livery the oil cap and fuel strainer drain Port is missing, please see my PR in the textures repo

**Comment by HHS81** [comment]
@hbeni  please see my answer on your PR :-)

**Comment by hbeni** [comment]
Hi @HHS81, i don't know what you mean...
What is the reason for it missing?

**Comment by HHS81** [comment]
@hbeni the PR has been reviewed and merged by Gilberto two days ago. I invited you already as collaborator - that was my last message on the PR. 

What didn't happend is, that the changed liveries wasn't pushed to this repository here. I have to add my texture changes before we can.

**Comment by HHS81** [comment]
@gilbertohasnofb @hbeni 
I added the winterkit texture to texture-repo. 
I also just added the Default.png and Blank.png with oil cap and fuel strainer drain Port. 
I also removed the alpha channel from all other liveries.
**IMPORTANT:** 
Future liveries may have the texture for the winterkit, but this layer is not really needed (just to make sure there is no future conflicts and we don't loose it). The existing liveries doesn't need to be changed, as the default livery "_Default.png_" in `/Models` is used as source by the winterkit 3d-model.

**Comment by gilbertohasnofb** [comment]
@HHS81 It's all clear, thanks for all the info.

**Comment by hbeni** [comment]
@HHS81 Very nice work!
I walked around my c128s several minutes to marvel at the fabulous winter-kit.

We did make very good progress with the plane the last months. It would be cool if you could find some time to model the bag in the cockpit and the POH so we can close #121.

**Pull request merged**
