### PR TITLE
Added stall horn test and prepared icing

### PR DESCRIPTION
**Pull request by hbeni**
This adds:
- stall horn function dependency on active breaker and electrical power (see POH 7-47)
- stall horn test switch property to test the horn on the ground
- prepared stall horn icing (piggybag on pitot icing)
- stall horn can theoretically fail now (`/controls/stall-horn/serviceable` -> false)

Open:
- [x] add exterior clickspot (only in `.ac` file currently)
  - [x] verify blender model
- [x] add texture
- [x] add checklist item to preflight (left wing leading edge / POH 4-11) (was already there)

image

### CODE REVIEW

**Comment by hbeni** [comment]
@HHS81 It would be cool if you could add a suitable clickspot (or even model?) to the wing so we can test the stall horn in preflight

Once we have merged this, we can also merge it into the pitot icing branch and enable the icing feature (just comment out the prepared code in `c182-sound.xml`)

**Comment by HHS81** [comment]
@hbeni 
after responding to a lot of things from you I take a break and concentrate on my things here again. Especially as my PRs have been again ignored to be merged. And I didn't find time to finish the icing feature yet

**Comment by hbeni** [comment]
No rush!
Glad to hear that your windows issues are solved (are they?)

I am not familiar with the merge policy in this project and currently think, that you should have the last word on merging at least for non trivial things, including your own pull requests. Would you like to handle it differently, esp. do you want (for example) me to review and merge your (and also mine) requests?

(I just dont dared to merge your stuff)

**Comment by HHS81** [comment]
@hbeni 
Usually I follow the same rules like the c172p does: Peer-Review. 
That means someone creates a PR, and the other members check if there are any issues.
4 eyes sees more issues/ problems than just 2. I found it quite helpfull in the past.
I thought that was clear. 😕 

And it seems my computer issues are solved - runs better than before. Must change my virusscanner sometime....

**Comment by hbeni** [comment]
New stall vane on livery:
image

**Comment by hbeni** [comment]
Ok, now waiting for the external clickspot, then we are ready.

@HHS81 Should i prepare in the clickspot in the `.ac` file and you port it over if you get time? Or if i change the blend file, how can i generate the `.ac` file from it?

**Comment by HHS81** [comment]
Don't get me wrong: it is basic knowledge how to alter and modify a .blend-file and export it to .ac-file. But if you don' t know how it works, it is better you wait with any 3d-work until I find some time this week! There is no rush,  no Deadline, it is not a commercial project and no User pays us any money.

**Comment by hbeni** [comment]
No problem, i just fear to break the main model. I already introduced you hours of unneeded work, so i better wait :)
My comment served just as some sort of "i'm ready"-flag.

**Comment by gilbertohasnofb** [comment]
@hbeni

> New stall vane on livery

That's cool, thanks for adding this! Is this already working with all liveries or will I need to manually add to the other ones?

**Comment by hbeni** [comment]
@gilbertohasnofb No, i added it to all liverys and also the normalmap. I also updated (and already published) the c182-Textures repo; so this should be ok.

**Comment by gilbertohasnofb** [comment]
>  I also updated (and already published) the c182-Textures repo; so this should be ok.

That's perfect, many thanks

**Comment by hbeni** [comment]
@HHS81 In 124233e i tried to add the clickspot to the model (hope i did it right).
However if i try to export the exterior model, i get only 2.1MB instead of the expected 2.7; and also flightgear quits with a segfault.

I activated all layers from the left box and then selected all the visible objects using border-select. I only activated the "selection only" option from the blender AC-Export menu.

What am i doing wrong?

--------------------
When i open the current .ac file and port the clickspot over from the blend file, and then export, all seems fine (even with only 2.1MB exported file size!); (this is the current state of the branch so it is basically merge-ready - however, i surely want to learn what i do wrong with the export, so i can assist better in the future)

**Comment by HHS81** [comment]
@hbeni 
> What am i doing wrong?

Not listen to me: 
> But if you don' t know how it works, it is better you wait with any 3d-work until I find some time this week! There is no rush, no Deadline, it is not a commercial project and no User pays us any money.

Then:

> so i can assist better in the future

I don't need any assistence in 3-modelling.

You might find me now quite arrogant, but this are those things which costs me most of the time- reviewing and explaining. Time which I could spend on other things on this project. 

Honestly said I don't like the way this project is going! 

The project started years ago in semester breaks, when I actually had some time left, originally as practice in 3d-modelling, texturing and rendering and with that as a completely private project. I never thought that I will publish it, until Gilberto came up on the forum and I offered the model to FlightGear.
Work could be mostly only done in semester breaks, since I spend every second weekend financing study by working in my previous job, and the other weekend I was happy to get some free time for me.
Yep, studying as an 30+ old man can be hard. 

FlightGear is a project which was and is developed in free time, without any payment. It isn't commercial and so this project here it is. The Cessna 182S should have been always be a fun project for me. Yes, aiming for realism - but always in a balance with other things in life, and especially in balance with what is possible and what is useful in FlightGear- pain-to-gain ratio.
Now more and more I feel under pressure; don't find time for my other FlightGear projects like the Dornier 328, EC135 or the BO105. 

I don' mind help by others in developing aircraft, quite in the opposite I'm happy that teamwork is easier and I can see it is commonly now accepted in FlightGear. Other then like years ago...

But when a house in real life is built, you won't see a plumper raising the roof; and the elctrician won't build up the walls. 
Imagine what would happen in real-life if it wouldn't be like that? 

I'm a strong 3d-modeller, have some basic knowledge in texturing and some minor to basic knowledge in coding nasal scripts. Gilberto has a lot of strength in texturing and creating sounds, while you are very strong in coding.

Let's keep it to that; and slow down a lot. Rome wasn't built in one day and so this aircraft.

**Comment by hbeni** [comment]
@HHS81 sorry that i made you feel pressurized by me. It is not my intend. I'm just curious how those things work and want to learn, especially in areas where i have no idea about, like kodelling and texturing.

It is perfectly fine for me what you have written and i can understand your toughts. I wil try to lessen my urge.
If i open issues or pull requests, or mention you, please dont think i need immediate attention. I mostly do this so it does not get forgotten and can be picked up easily in the future.

**Comment by hbeni** [comment]
@HHS81 hello Heiko,
with failures merged now, it would be very cool to also have the stall vane testable in preflight.
All needed for merge is that you check my modified blender model...

Do you think you can split off some minutes for his somewhere soon?

**Comment by HHS81** [comment]
I will take a look this week, I think I will find some time.

**Comment by HHS81** [comment]
@hbeni 
I have reviewed the .blend-file.
I saved it as Legacy-format. So it can be opened with older Blender-Versions as well without any errors, and the size of the file much smaller.

**Comment by HHS81** [comment]
So it will be merged.

**Comment by hbeni** [comment]
Thank you very much! 
So my blender version is too old?

**Comment by HHS81** [comment]
@hbeni 
nope.
Blender 2.50 and newer saves much more information then we actually need for FlightGear. Especially the Ngons can`t be read by older Blender versions, so models exported from 2.50+ to Blender 2.49 will have  edges only, but no faces.

**Pull request merged**
