### PR TITLE
Issue200 (Implement external heat)

### LINKED ISSUE #200: Priming influenced by OAT / External heat
When complex engine procedures are on:
- [x] Make priming ammount influenced by outside temperature when engine is cold
- [x] Add external heater feature to allow preheat in cold weather
- [x] Add external heater model and sound

### PR DESCRIPTION
**Pull request by hbeni**
- [x] fixed #200, now priming is depending on outside temperature. To enable priming in cold weather, external heater has been added.

- [x] Model and sound is still missing, can somebody add the 3D model and sound?
The property in question is /engines/engine/external-heat/enabled

See https://github.com/HHS81/c182s/issues/200#issuecomment-349787118 for a picture

### CODE REVIEW

**Comment by hbeni** [comment]
I just had an idea how this could be implemented more easily with some nasal help, allowing us to show heated oil temp in the gauge.

I will try this out.

**Comment by hbeni** [comment]
Ok, it worked out: System is simpler now AND supports showing the raised oil temp when external heater is applied :)
@HHS81: Apart from the 3D-Model, this should be ready for merge!

**Comment by HHS81** [comment]
@hbeni 

> Ok, it worked out: System is simpler now AND supports showing the raised oil temp when external heater is applied :)

Does it also simulate the raising battery-capacity from my Merge Request [#199](https://github.com/HHS81/c182s/pull/199) when external heater is applied?

**Comment by hbeni** [comment]
Not yet, beause i thought that the heat doe not reach the battery. Where is the battery mounted?

**Comment by HHS81** [comment]
The battery is somewhere under the cowling, I guess near the ground power plug. No idea how much the battery is affected by the engine heat, but it is affected by the preheater very well.

**Comment by hbeni** [comment]
d08603f adds heater heating battery

**Comment by hbeni** [comment]
(resolved conflict with cowling-temperature for battery capacity after merge to master)

**Comment by HHS81** [comment]
@hbeni 

> (resolved conflict with cowling-temperature for battery capacity after merge to master)

And that's the reason why I prefer that even small PR will be merged into master instead of other branches. It is easier to follow and prevents conflicts later.

**Comment by HHS81** [comment]
O.k. I added the Engine PreHeater.

I modelled the [RedDragon Engine PreHeater 300 ](https://flameengineering.com/collections/engine-preheaters/products/self-contained-12-volt-d-c-preheater-kit-model-h-175-200), you can find more infos [here](https://cdn.shopify.com/s/files/1/0781/4013/files/product_pdf_124.pdf?14023245904148787307).

I don't think it does much noise, so we could skip the sound.

@gilbertohasnofb  you will find in Models/Exterior the Texture/UVmap. It is 2048px x2048px, but less later is also o.k.

**Comment by HHS81** [comment]
fgfs-screen-004

**Comment by hbeni** [comment]
Looks really great!!!

**Comment by gilbertohasnofb** [comment]
> you will find in Models/Exterior the Texture/UVmap. It is 2048px x2048px, but less later is also o.k.

I will take a look at this as soon as I can and push my commits to this very same PR, so please do not merge this before the textures are ready

**Comment by HHS81** [comment]
@gilbertohasnofb  no rush

**Comment by gilbertohasnofb** [comment]
@HHS81 Do you have any photographs you used as reference for the model? The previous photograph that @hbeni uploaded is for a slightly different model:



Else I will just use some common sense when making the textures.

**Comment by HHS81** [comment]
@gilbertohasnofb   I modelled the [RedDragon Engine PreHeater 300](https://flameengineering.com/collections/engine-preheaters/products/self-contained-12-volt-d-c-preheater-kit-model-h-175-200) , you can find [more infos here](https://cdn.shopify.com/s/files/1/0781/4013/files/product_pdf_124.pdf?14023245904148787307).

**Comment by gilbertohasnofb** [comment]
Great, many thanks!

**Comment by HHS81** [comment]
@gilbertohasnofb  https://www.youtube.com/watch?v=BNCVuxpYWsA

**Comment by gilbertohasnofb** [comment]
Thanks Heiko, that will help with the sound as well (though I imagine the sound would be more muffled once it's connected to the plane).

**Comment by HHS81** [comment]
@gilbertohasnofb  https://www.youtube.com/watch?v=ZC5LhItlWMo

**Comment by gilbertohasnofb** [comment]
@HHS81 Textures are done, I just pushed the commit. This is how it looks:

fg-0

fg-1

But there are a couple of issues with the model, Heiko. There are some holes, the main hose is not aligned with the heater and there are collisions with the propeller and the aircraft nose, see:

fg-2

fg-3

fg-4

fg-5

fg-6

**Comment by gilbertohasnofb** [comment]
Working on the sound now, should push it soon.

**Comment by gilbertohasnofb** [comment]
@hbeni the sound you requested is pushed, the file is named `preheater.wav` and is located in the `Sounds` folder. Could you please implement it in the xml code?

**Comment by hbeni** [comment]
Yes, i will try to implement this!

**Comment by hbeni** [comment]
@HHS81 @gilbertohasnofb I integrated the sound, it's ready for you testing!

**Comment by gilbertohasnofb** [comment]
@hbeni the sound is working fine, thanks for implementing this. So I think the only things left on this PR is to fix those small issues with the 3D model.

**Comment by HHS81** [comment]
@hbeni  and @gilbertohasnofb 
I fixed the issues with the 3d-model. 
Ready to be merged!

**Comment by gilbertohasnofb** [comment]
@HHS81 are you sure you pushed your modifications? I don't see any difference on my side and I don't see any new commits by you listed in this PR

**Comment by HHS81** [comment]
I pushed it into branch `issue200`

**Comment by gilbertohasnofb** [comment]
now your commits are showing, I will check it in the sim and merge this

**Comment by gilbertohasnofb** [comment]
Looks excellent, thanks for the fixes.

**Comment by hbeni** [comment]
Great teamwork, this was fun!

Am 2017-12-17 0:15, schrieb Gilberto Agostinho:

**Pull request merged**
