### PR TITLE
Add compass correction card (texture by @hbeni)

### LINKED ISSUE #495: Magnetic Compass: Add deviation table
https://en.wikipedia.org/wiki/Magnetic_deviation

The compass has magnetic deviation, and this must be compensated using a table.
That table is usually shown below the compass.

The table is here:
https://github.com/HHS81/c182s/blob/8befd6b94d2087340dbb522453c88474ae75c919/Systems/instrumentation.xml#L93-L150

----
The DA40NG has such a card

### PR DESCRIPTION
**Pull request by TheFGFSEagle**
fix #495

### CODE REVIEW

**Comment by TheFGFSEagle** [comment]
Done ! (for the 182S - if you want me to add it for the T too I need a photo for the correct placement).

**Comment by hbeni** [comment]
Hm, i think the placement is not standardized, so we could put it where we want.

Which brings me to an idea, can we easily move it more to the topleft and make it 75% the size (the original is even smaller)?
grafik

**Comment by hbeni** [comment]
Checked the lights, looks good!
One small thing is when activating the cabin lights (the ones at the top) it does not illuminate the card

grafik

**Comment by TheFGFSEagle** [comment]
Moving and resizing is no problem at all ! :) The thing with the lighting is more complicated however … does anyone still have the Blender file with which the cockpit lightmaps were created ? The two in the dev folder don't contain any light sources that could be used for lightmap baking ! :(

**Comment by TheFGFSEagle** [comment]
Hmm, yeah, I guess I can copy the main lightmap and crop it to the right position and size.

**Comment by TheFGFSEagle** [comment]
I think we can spare the extra lightmap - @hbeni, please see if it looks good enough now, and if it does please merge and close this pull request ! 😃

**Comment by hbeni** [comment]
Thank you Eagle!

**Pull request merged**
