### PR TITLE
updated Uber-shader

### PR DESCRIPTION
**Pull request by HHS81**
#152 Cessna 182 s now using the updated Uber-shader with fresnel effect, and selectable additional reflection coloring model

### CODE REVIEW

**Comment by HHS81** [comment]
@gilbertohasnofb @wlbragg  ping

**Comment by wlbragg** [comment]
Thanks!

**Comment by gilbertohasnofb** [comment]
@HHS81 is this ready to be merged or is there still any work left to do? I will try to take a look at it soon, but I am quite busy this weekend

**Comment by gilbertohasnofb** [comment]
@HHS81 one more thing, are these modifications to the shader shipped with FG 2016.4? I am using only stable releases since some time, as I don't have the patience to compile FG on Linux, and downloading the lastest versions via the PPA sometimes breaks everything and I end up without FG for a couple of days :cry:

**Comment by HHS81** [comment]
seems not. But you need just to download https://sourceforge.net/p/flightgear/fgdata/ci/next/tree/Effects/model-combined.eff and https://sourceforge.net/p/flightgear/fgdata/ci/next/tree/Shaders/model-ALS-ultra.frag

**Comment by gilbertohasnofb** [comment]
@HHS81 just notice the new changes, is this PR ready to be merged?

**Comment by HHS81** [comment]
Not yet, in a few minutes!

**Comment by gilbertohasnofb** [comment]
No rush. Once this is ready let me know and I can test it here.

**Comment by HHS81** [comment]
O.k, this updates following things:

1. enables real fresnel on the exterior-surfaces
2. fix Issue #43 by enabling domelights in the cabin and add exterior lights (under the wing)
3. fix broken fairing animation

Ready to be reviewed and merged

**Comment by gilbertohasnofb** [comment]
> fix Issue #43 by enabling domelights in the cabin and add exterior lights (under the wing)

Looks really good, those interior domelights look stunning.

> fix broken fairing animation

I don't know what was broken on it, but it is looking good on my side

> enables real fresnel on the exterior-surfaces
  
It looks like the fresnel shader is completely broken on my Intel card:

screenshot from 2017-08-27 19 34 07
  
I can only run the c182s with the Model shader set to minimum. So unfortunately it looks like I can't test that.
    
And by the way, it has been quite a while since I last fired up FG so I don't know if this is some issue on my side or not, but when I tried to select the liveries submenu nothing happened and the console registered these errors, do you also see it in your `ShaderTest` branch?

> Nasal runtime error: No such member: dialog
>  at /sim/bindings/menu/binding[100], line 1

**Comment by gilbertohasnofb** [comment]
So if you are happy with the fresnel look on the exterior and if yo don't see those error messages, then I guess we can just go ahead and merge this. I will later test on my other computer which has a different GPU (non-Intel).

**Comment by HHS81** [comment]
> Looks really good, those interior domelights look stunning.

Thanks!

> I don't know what was broken on it, but it is looking good on my side

I forgot to add the tags to the livery-files and Benedikt accidently added the not-working tags from the c172p. 

> It looks like the fresnel shader is completely broken on my Intel card:

Uh, bad. How does the c172p looks like?
The new shader doesn't even work in Rembrandt...

> And by the way, it has been quite a while since I last fired up FG so I don't know if this is some issue on my side or not, but when I tried to select the liveries submenu nothing happened and the console registered these errors, do you also see it in your ShaderTest branch?

My FG isn't up to date, though it is at least 2017.3.0. But I can't see any any errors in this branch.

**Comment by HHS81** [comment]
> So if you are happy with the fresnel look on the exterior and if yo don't see those error messages, then I guess we can just go ahead and merge this. I will later test on my other computer which has a different GPU (non-Intel).

Sure!

**Comment by gilbertohasnofb** [comment]
> Uh, bad. How does the c172p looks like?

c172p is looking fine:

screenshot from 2017-08-27 20 25 36

Is there some specific feature you are using in the c182s that is not used in the c172p?

> My FG isn't up to date, though it is at least 2017.3.0. But I can't see any any errors in this branch.

It shouldn't be a problem then, I think I have a mismatch between FG and FGDATA versions. I will take a proper look at it later, but if you are not seeing these errors then it's certainly only on my side.

**Comment by HHS81** [comment]
> Is there some specific feature you are using in the c182s that is not used in the c172p?

Not that I know.....
This is indeed strange

**Comment by gilbertohasnofb** [comment]
Are you sure the fresnel shader is being used by the c172p? Anyway, if you can think of anything I would be very happy to test it here on my side.

The only way of using the c182s on Intel cards is to complete disable the Model shader slider in custom shader sliders.

**Comment by HHS81** [comment]
> Are you sure the fresnel shader is being used by the c172p?

At least in the master-branch. Can't tell if on FGAddon.

**Comment by gilbertohasnofb** [comment]
I used the `master` branch of the c172p in that screenshot (I never use the FGAddon one).

**Comment by HHS81** [comment]
can you disable the normalmap in the `c182sreflect-uber.eff`  and see what is happening?

**Comment by gilbertohasnofb** [comment]
I changed line 8 into '<normalmap-enabled type="int">0</normalmap-enabled>' but the same issue persists.

**Comment by gilbertohasnofb** [comment]
@HHS81 I actually figured out what was happening. It turns out not only that error message concerning the livery dialog but also this shader conflict was being caused by an incompatible FGDATA version. I changed to the correct branch and suddenly the plane displays perfectly well again! Sorry for the noise and thanks for the great work, this plane looks stunning.

**Comment by gilbertohasnofb** [comment]
@HHS81 when I turn on the right front upper light (see first image), two lights appear under the wings. Is that a feature?

screenshot from 2017-08-27 22 24 46

screenshot from 2017-08-27 22 25 40

**Comment by HHS81** [comment]
The lights below the wing bottom surface should be switched on together with the rear dome light. Copy and Paste error. I will fix it soon as I find time.

**Comment by HHS81** [comment]
Fixed

**Pull request merged**
