### PR TITLE
Implement #67 - spiral cable from yoke to panel

### PR DESCRIPTION
**Pull request by TheFGFSEagle**
Added spiral yoke map light cable, and (hopefully) fixed yokes graphics glitch for some graphics cards (https://forum.flightgear.org/viewtopic.php?f=4&t=28475&start=15#p395288) by assigning `model-transparent-combined` to the yokes + yoke cables

### CODE REVIEW

**Comment by HHS81** [comment]
> Added spiral yoke map light cable, and (hopefully) fixed yokes graphics glitch for some graphics cards (https://forum.flightgear.org/viewtopic.php?f=4&t=28475&start=15#p395288) by assigning `model-transparent-combined` to the yokes + yoke cables

From the effect file: "It's kept for backwards compatibility and should not be used on new projects." Can you tell me why you did assigne "model-transparent-combined" to the  yoke?
Your explanation link is leading to an old forum thread with nothing about the problem...

**Comment by TheFGFSEagle** [comment]
Well, making the cable come out of the panel directly below the yoke mount should be fairly easy ! The bend, though, I've tried already by cutting the cable in three pieces (or actually, 5, but the first and last just move with the yoke / are attached to the panel) but I had some trouble making the animation of the cable fit the animation of the yoke (on my 210). But I can retry by using just two pieces with a locked track animation … that should work. But the cable would get an really sharp pointing tip in the middle ?

**Comment by hbeni** [comment]
Hm, as close to the footage as possible would be nice.
Didn’t the c172 have a bent already?
For sure also the c208 grand caravan

**Comment by TheFGFSEagle** [comment]
For the glossyness, I guess I can use the c182s_controls effect ?

**Comment by TheFGFSEagle** [comment]
The 172 has a very small bend in the cable AC file, and that just get's scaled. As for the 208's yoke cable, it's also just one piece that gets scaled … :(

**Comment by TheFGFSEagle** [comment]
I'll see if I can get something better, with three parts and two locked track animations. But actually, this is vertex shader territory … but unfortunately I don't know that AT ALL !

**Comment by HHS81** [comment]
> I'll see if I can get something better, with three parts and two locked track animations. But actually, this is vertex shader territory … but unfortunately I don't know that AT ALL !

Have a look into wlbraggs Aircrane- he animated the hose. The animation is quite similar to that needed for the cable. Nom need for vertex shaders

**Comment by hbeni** [comment]
Awesome bending!
Can you tune the bending a little more, so its bend somewhat when the wind gust lock is installed, like in the picture?

**Comment by TheFGFSEagle** [comment]
You mean, that it has a little bend already when the yoke is in the neutral position ?

**Comment by TheFGFSEagle** [comment]
@HHS81 sorry about not replying to your comment - I completely overlooked it !

> > Added spiral yoke map light cable, and (hopefully) fixed yokes graphics glitch for some graphics cards (https://forum.flightgear.org/viewtopic.php?f=4&t=28475&start=15#p395288) by assigning `model-transparent-combined` to the yokes + yoke cables
> 
> From the effect file: "It's kept for backwards compatibility and should not be used on new projects." Can you tell me why you did assigne "model-transparent-combined" to the yoke? Your explanation link is leading to an old forum thread with nothing about the problem...

Well, the post itself doesn't contain anything about the yoke transparency problem, but the video included _does_ ! As to why I assigned the effect - to fix exactly that problem, as I was getting it too. I didn't know it was deprecated, but I removed it again anyways as it didn't change anything. May I ask why we don't simply hide the yokes, like the C172P ?

**Comment by TheFGFSEagle** [comment]
There you go !

**Comment by hbeni** [comment]
> May I ask why we don't simply hide the yokes, like the C172P ?

Because :)
You *can* hide them completely if you adjust the transparency setting from the crafts menu.
The option enhances user experience for people like me that still want feedback where the yoke is but also want to see the panel behind it.

**Comment by hbeni** [comment]
> @hbeni: There you go !

Will investigate soon

**Comment by hbeni** [comment]
Looks good, thank you very much for the addition! :)

**Comment by HHS81** [comment]
> 
> Well, the post itself doesn't contain anything about the yoke transparency problem, but the video included _does_ ! As to why I assigned the effect - to fix exactly that problem, as I was getting it too. I didn't know it was deprecated, but I removed it again anyways as it didn't change anything. May I ask why we don't simply hide the yokes, like the C172P ?

The linked thread has already more than 13 pages and several videos. 
Since you are new to FGFS a little rule I had to learn myself years ago when I started with FGFS: if you think it is a bug- it is in fact a feature. 
😸

**Comment by TheFGFSEagle** [comment]
> The linked thread has already more than 13 pages and several videos.
It's on the last / first page ! ;) Also the link is a direct link which should take you directly to the right post with the video …

**Comment by HHS81** [comment]
> > The linked thread has already more than 13 pages and several videos.
> 
> It's on the last / first page ! ;) Also the link is a direct link which should take you directly to the right post with the video … (the description of the post only says something about a lighting problem, but you can also see the yoke problem in it)

No, it´s not. That`s the link you posted: https://forum.flightgear.org/viewtopic.php?f=4&t=28475&start=15#p395288
Links to the second page of the thread (from 29. dec. 2015)

And that´s the link you should have posted: https://forum.flightgear.org/viewtopic.php?f=4&t=28475&start=150#p395286 (from nov. 2021)

Please compare it. 

The yoke problem is a problem inside FlightGear, not the aircraft itself. There is the rule that in FlightGear we won`t make changes to aircraft just for fixing issues caused by internal bugs. 

The lighting problem of the C182T panel is a configuration problem of the effect file combined with the 3d-model.  The prerendered lightmaps are not matching the panel since it changed, and should be rerendered.

**Comment by TheFGFSEagle** [comment]
@HHS81 okay, now I get it … I have reversed my sorting order so that I get the newest post on the first page, instead of the oldest … I didn't know this makes a difference when sharing a link to a reply. Sorry.

**Comment by HHS81** [comment]
> @HHS81 okay, now I get it … I have reversed my sorting order so that I get the newest post on the first page, instead of the oldest … I didn't know this makes a difference when sharing a link to a reply. Sorry.

Nether mind. I´m pretty sure it should not make any difference. Maybe a bug in the software used by the forum?

**Pull request merged**
