### PR TITLE
Initial Cessna 182T with FG1000 glass panel.  Also fixes JSBSim errors.

### PR DESCRIPTION
**Pull request by stuartbuchanan**
Initial C182T glass panel.

Also a completely separate commit which fixes JSBSim errors which were stopping the 182T (and S) from loading.

### CODE REVIEW

**Comment by HHS81** [comment]
@stuartbuchanan 
Thanks so far! 
But it seems you didn`t work from the latest commits by Benedikt and me, especially not from FGAddon! 😄 
JSBSim errors on the C182S has been fixed there for a while. I also notice, that at the beginning I get a black aircraft - another bug, we already fixed some weeks ago.

Instead I get following error:    
  ```
 24.26 [ALRT]:nasal      Nasal runtime error: setprop() value is not string or number
   24.26 [ALRT]:nasal        at E:/AirCraftAddon/c182s/Nasal/engine.nas, line 283
   24.26 [ALRT]:nasal        called from: C:/Users/Heiko/FlightGear/fgdata/Nasal/globals.nas, line 119
```

Something I don`t get with the Cessna 182S. Also the autopilot isn`t working.
I have to compare your fork, and our master-branch to see ths difference and update this PR.

I think also, that it is better that I give you commit rights here, it is easier than working from a fork. Agree?

**Comment by hbeni** [comment]
Cool that you work on it!

I agree, collaborating here would be a good place.
Maybe it is a good idea to fork off a new branch from current master and integrate the changes from your repo there?

**Comment by HHS81** [comment]
@stuartbuchanan I have created a new branch called `C182T`, merged and synchronized your files manually. Unless I forgot something, the branch `C182T` is uptodate, and all errors removed. 
So you can work from this branch on. Please @stuartbuchanan @hbeni @gilbertohasnofb check if everything is correct, then I will merge the the branch into master. I think #258 will give us a roadmap.

**Comment by HHS81** [comment]
Btw.: @stuartbuchanan  https://github.com/HHS81/c182s/invitations

**Comment by stuartbuchanan** [comment]
Great.

Thanks very much for setting this up for me.  Looking forward to working
more closely with you all on the project.

**Comment by hbeni** [comment]
I briefly checked.
Looks promising so far :)

I will add my findings to the Issue you mentioned above (#258), so we have everything in one place.

**Comment by wlbragg** [comment]
Looks like it is working for me! Still trying to get my bearings on the glass settings and operations.

**Comment by wlbragg** [comment]
Spoke too soon, I don't know if this is a leftover thing or what, but I got a black exterior fuselage until I changed liveries.

**Comment by wlbragg** [comment]
I may be using Stuart's branch and not the new one which might explain the black exterior.

**Comment by HHS81** [comment]
Maybe I close PR since we already have a branch with the commits by Stuart, and discuss further in #258.

**Pull request merged**
