### PR TITLE
New tow bar model

### PR DESCRIPTION
**Pull request by MariuszXC**
New tow bar.
Currently parts are not joined into one object, to allow for fine tuning. Can be either joined in Blender (which is kind of permanent) or using FG animation (leaves space for future modifications - probably preferred).

### CODE REVIEW

**Comment by hbeni** [comment]
Cool, that was quick.

This is how its rendered here:
grafik

Would have expected a more saturated blue and black of the handle and the grips.
And a little bigger, maybe?

grafik


----
Just had a quick shot at scaling:
grafik

But I think it should extend more to behind the prop spinner?

**Comment by hbeni** [comment]
https://www.aopa.org/-/media/Images/AOPA-Main/News-and-Media/Publications/Flight-Training-Magazine/1710f/1710f_pf_tow/1710f_pf_tow_16x9.jpg

**Comment by hbeni** [comment]
Had a shot at it.
Looks good, doesn't it?
grafik

**Comment by hbeni** [comment]
Now only question remaining is, why the color is so off?

**Comment by MariuszXC** [comment]
Dimensions (lenght = 39.5" ) were taken directly from the shop site. Other were eyeballed from the product pic.
Color is off, because you probably need to apply an effect to the object. Actually, the rubber handle ends would need to be excluded from this effect, because rubber is dull, while paint is glossy.. I'll try to move the handle ends to separate objects..

**Comment by hbeni** [comment]
Merged in c284d41

Looks great, @MariuszXC !
Thank you!

**Pull request closed without merging**
