### PR TITLE
Issue383: Yaw due to aileron?

### PR DESCRIPTION
**Pull request by HHS81**
Fixed Yaw due aileron behavior - (probably wrong foresign in the data source); changed some parametres due longer ago JSBSim changes; made gears more springy as seen on real aircraft; synchronized c182t

### CODE REVIEW

**Comment by HHS81** [comment]
Would be cool, if this could be merged soon, so the KAP140 can be tuned to it

**Comment by hbeni** [comment]
Why are there so many commits listed above?
I assume we don't want all of them merged to master yet?

**Comment by HHS81** [comment]
> 
> 
> Why are there so many commits listed above?
> I assume we don't want all of them merged to master yet?

Oh. damn, I think I have merged master into some while ago.... I will make a new pull request

**Comment by HHS81** [comment]
faulty push request- new one on the way

**Pull request closed without merging**
