### PR TITLE
Added mechanical damping to elevator and ailerons

### PR DESCRIPTION
**Pull request by hbeni**
Related to PR #576 / Issue #575

I think it would also be beneifical to add some damping for the ailerons and elevator, like with the C172?

### CODE REVIEW

**Comment by hbeni** [comment]
@HHS81 @Octal450 
Does this also make sense?

**Comment by Octal450** [comment]
This is not the way to do it.
This doesn't really damp anything. 

If you're going to add damping, it depends on what reason?

If you're doing it to make a better approximation of joystick vs real yoke pilot commands, then you should be using a lag filter not a kinematic. I use a c1 of 20 on the PA28. (and you can make the yokes animate off this too for full effect)

otherwise, you need to add aerodynamic calculations.

Just using a kinematic to "slow" the input is not the right way to do it and unrealistic. The c172 should change to a lag filter as well.

Kind Regards,
Josh

**Comment by hbeni** [comment]
Thanks Josh for the feedback!

> Just using a kinematic to "slow" the input is not the right way to do it and unrealistic. The c172 should change to a lag filter as well.

- But why was that solution for the rudder accepted then a few days ago?
- I had tought, that the kinematic simulates the time it takes mechanically to move the respective surface mechanically;
so "damping" is maybe not the correct term
- what is the difference between a kinematic and the lag-filter?

----

@wlbragg Ping for info / C172 affected

**Comment by HHS81** [comment]
> Thanks Josh for the feedback!
> 
> > Just using a kinematic to "slow" the input is not the right way to do it and unrealistic. The c172 should change to a lag filter as well.
> 
> * But why was that solution for the rudder accepted then a few days ago?
> * I had tought, that the kinematic simulates the time it takes mechanically to move the respective surface mechanically;
>   so "damping" is maybe not the correct term
> * what is the difference between a kinematic and the lag-filter?
> 
> @wlbragg Ping for info / C172 affected

The front gear does indeed have a mechanical damper to prevent shimmering. 

But all other controll surface does not have- they are not hydraulically linked, just pure wires. So the lag is very small, if even noticeable. I have no idea why the c172p folk did add it. 

Kinematic: Encapsulates a kinematic (mechanical) component for the flight control system- simulation of mechanics.
Lag-filter: damping, filtering of input/ output

**Comment by Octal450** [comment]
Agreed with HHS.

Pls remove your change to the rudder. This should not have been accepted. c172 team also should remove. No idea why they did. 

To clarify:
"RECREATING" flight control slop by artificially limiting the travel of the surface is "CHEATING" and unrealistic. The behavior should be done in aerodynamics.

There is no hydraulics, so no rate of change (kinematic) delay should be added.

A lag-filter is a low-pass filter. I added it to the flight control inputs to reduce the "artificial instantaneous" behavior of potentiometers in our sticks. If you compare a "human yoke movement" to the output of your joystick with a 20c1 lag filter applied, you will find they are quite similar.

This also has the helpful side-effect of reducing pot noise that all controllers suffer from.

Kind Regards,
Josh

**Comment by Octal450** [comment]
@HHS81 
I apologize for nagging you here, I sent you an email back in January, while you're here I wanted to double check that you received it.

Kind Regards,
Josh

**Comment by HHS81** [comment]
> @HHS81 I apologize for nagging you here, I sent you an email back in January, while you're here I wanted to double check that you received it.
> 
> Kind Regards, Josh

Oh, I'm sorry, I can't remember recieving anything from you. Which of my Email-Adress you used? 

You might resend the message on the official FlightGear Forum as PN, that will prevent that your message will land again in the spam ordner.

**Comment by Octal450** [comment]
@HHS81 ,
No problemo, I found your email from the mailing list (I won't paste here for privacy), as the forum does not permit me to contact you. Perhaps you have PMs/Email turned off?

image

Kind Regards,
Josh

**Comment by HHS81** [comment]
> @HHS81 , No problemo, I found your email from the mailing list (I won't paste here for privacy), as the forum does not permit me to contact you. Perhaps you have PMs/Email turned off?
> 
> image
> 
> Kind Regards, Josh

Indeed, but should be possible now.

**Comment by Octal450** [comment]
Sent, thank you!

**Comment by hbeni** [comment]
So, just to be sure, if I replace the kinematic with your PAs lag filter for rudder, aileron and elevator is the correct solution?

**Comment by Octal450** [comment]
What problem are you trying to solve?

I use it for PC joystick to real yoke "approximation".

If you are trying to change the way it flies, then that's a completely separate issue that needs to be addressed via aerodynamics modifications.

Kind Regards,
Josh

**Comment by HHS81** [comment]
> Sent, thank you!

Thanks, recieved, I'll answer tomorrow and maybe I can even prepare some files for you.

**Comment by hbeni** [comment]
> What problem are you trying to solve?

The initial problem I wanted to solve was that my rudder pedals seemed to be very sebsitive, and others reported that too (so no hardware/joystick issue).
I think it reacts better now that the rudder acty needs some (small!) time to actually travel.
And given that with the mouse i can move the aileron from -1 to 1 in a frame, that should not be possible in the real world (think alone the wires friction). I have seen the kinematics in the 172 and tought, they are there for a (that) reason, so i ported the kinematic over here.
Now the elevator, rudder and ailerons can travel still really fast, but not instant anymore.

**Comment by Octal450** [comment]
I am sorry but this is a flight dynamics issue, NOT a flight control issue.

The lag filter fixes the "instanteous -1 to 1 in one frame" without making it behavior like a actuator rate.

Kind Regards,
Josh

**Comment by hbeni** [comment]
Hence my query:
> So, just to be sure, if I replace the kinematic with your PAs lag filter for rudder, aileron and elevator is the correct solution?

**Comment by Octal450** [comment]
Oh yes, now I understand what you meant. My mistake.

Yes, I agree.

Kind Regards,
Josh

**Comment by hbeni** [comment]
Great, I‘ll prepare a PR then.

**Comment by HHS81** [comment]
> > What problem are you trying to solve?
> 
> The initial problem I wanted to solve was that my rudder pedals seemed to be very sebsitive, and others reported that too (so no hardware/joystick issue). I think it reacts better now that the rudder acty needs some (small!) time to actually travel. And given that with the mouse i can move the aileron from -1 to 1 in a frame, that should not be possible in the real world (think alone the wires friction). I have seen the kinematics in the 172 and tought, they are there for a (that) reason, so i ported the kinematic over here. Now the elevator, rudder and ailerons can travel still really fast, but not instant anymore.




> > What problem are you trying to solve?
> 
> The initial problem I wanted to solve was that my rudder pedals seemed to be very sebsitive, and others reported that too (so no hardware/joystick issue). I think it reacts better now that the rudder acty needs some (small!) time to actually travel. And given that with the mouse i can move the aileron from -1 to 1 in a frame, that should not be possible in the real world (think alone the wires friction). I have seen the kinematics in the 172 and tought, they are there for a (that) reason, so i ported the kinematic over here. Now the elevator, rudder and ailerons can travel still really fast, but not instant anymore.

It is an more a human-hardware-software issue ;-)
Of course a mouse doesn't represent the real yoke, the friction of the wires and linkages and the aerodynamic forces of an aircraft. Not even the sim/ gamers yokes you can buy today. 
But yes- if you would add enough force to a real yoke, and ignore the structural breaking points of the yokes and mechanical linkages, you might be able to move the control surfaces in an instant! 

In reality the forces are too big. I only have 5-10min of stick time- but the aircraft was simulated in FGFS at this time by the pilot I flew with. And I can remember that I could control it with rather small inputs but needed still quite some forces to do- which felt weird as I was used to a mouse needing no force. 

We don't have force feedback- that's why some things will feel different and act different - no matter how realistic the fdm is.

**Pull request closed without merging**
