### PR TITLE
Implement #341(Integrate new default descriptive Properties)

### PR DESCRIPTION
**Pull request by hbeni**
Additional descriptive tags in aicraft-set.xml

### CODE REVIEW

**Comment by hbeni** [comment]
XML is sanitized and loads (here) without visible errors.

**Comment by hbeni** [comment]
Just another comment:
- i have no clue how to actually test this
- i chosed to use bare minimum POH values for the minimum runway length. Those are only achievable at sea level using stol techniques and thus not in all cases.
Should we maybe use more conventional values here? From the wiki i learned that the numbers may be used by the launcher to issue a warning and the map to hide shorter airfields...

**Comment by HHS81** [comment]
> 
> 
> Just another comment:
> 
>     * i have no clue how to actually test this
> 
>     * i chosed to use bare minimum POH values for the minimum runway length. Those are only achievable at sea level using stol techniques and thus not in all cases.
>       Should we maybe use more conventional values here? From the wiki i learned that the numbers may be used by the launcher to issue a warning and the map to hide shorter airfields...

I would choose the bare minimum POH - if users uses the aircraft in a realistic way, they would have made a flightplan, calculated fuel, calculated W&B, checked weather, and decided if the airport strip is long enough.

**Comment by hbeni** [comment]
Then we can merge 😁

**Pull request merged**
