### PR TITLE
Issue #137 (instruments glare)

### PR DESCRIPTION
**Pull request by hbeni**
Fix for #137

### CODE REVIEW

**Comment by HHS81** [comment]
Hmmm...

Davtron LCD-numbers aren't visible anymore.

**Comment by hbeni** [comment]
Hm, here they show (white). Sure you got the right branch (Issue137 at commit a3346b73a93)?
Can you investigate what is causing this, as i can't reproduce here?

**Comment by HHS81** [comment]
@hbeni I guess I fixed it

**Comment by HHS81** [comment]
I will merge it now, I don't see any issues!
Thanks again!

**Comment by hbeni** [comment]
Sorry, i need to reopen this PR since i detected a small glitch in the GMA (markers are dark at night with glareshield on)

Fix is on the way into this branch...

**Comment by hbeni** [comment]
fix is merged.

**Pull request merged**
