### PR TITLE
Extended failures (fix #242)

### LINKED ISSUE #242: Implement failures
@HHS81 do you already have plans how to implement failures?
What is the state of the [failuremgr](http://wiki.flightgear.org/Failure_Manager), or other fgfs standard infrastructure?

It would be cool to support also failures of the systems i recently made and integrated properties to do so (serviceable, and leakage in case of the fuel system)
edit: stall horn may fail now too! (see #256)

### PR DESCRIPTION
**Pull request by hbeni**
- [x] Implements custom failures. All major components and many minor ones can fail now.
There is a (i hope userfriendly) GUI to trigger the failures and also with two surprise-modes. The GUI also has quick access to the basic compat failure modes.

Random failure modes can be initialized by setting properties from the launcher, making the flight (and/or preflight) more funny.
```# Init failure modes in case requested by startup.
# This can be done by providing the following properties through the laucher or cli:
#  + random failures (fail at most n systems in max x time)
#     --prop:/sim/failure-manager/surprise-mode/ammount=<number>
#     --prop:/sim/failure-manager/surprise-mode/maxtime=<minutes> (optional, default 30)
#
#  + random surprise mode (fail one system every x minutes): 
#     --prop:/sim/failure-manager/surprise-mode/timer-active=1
#     --prop:/sim/failure-manager/surprise-mode/timer=<minutes>  (optional, default 30)
#
#  To also turn off screen messages, use:
#     --prop:/sim/failure-manager/quiet=1
#
```

fix #242 

- [x] add user switch that allows restoring failures from a previous session

### CODE REVIEW

**Comment by hbeni** [comment]
Ok, i think this is good now.

**Comment by HHS81** [comment]
I will test soon!

**Comment by hbeni** [comment]
Have fun and take your time!

**Comment by hbeni** [comment]
@HHS81 I also noticed, that failures are not persistent between sessions currently. I think it would be cool however.
Do you want me to add a user switch so failures can be reestablished after init of "saved" state selection? And if so, should it be activated by default (as there are no failures active unless user selects so)?

**Comment by HHS81** [comment]
I haven't tested it yet, but will soon.

**Comment by HHS81** [comment]
@hbeni: sounds very good! I think the user switch would be great!

**Comment by HHS81** [comment]
hmmm... why is there no sound?

**Comment by hbeni** [comment]
@HHS81 what sound exactly? Sound is working overall perfectly well here with this branch.

Before the merge, i want to add the user swich thingy.

**Comment by HHS81** [comment]
Hmmm... for some strange reasons I had no sound.... No I have.

**Comment by hbeni** [comment]
> Before the merge, i want to add the user swich thingy.

Done, tested and working  :)
image

**Comment by HHS81** [comment]
Great! That makes fun and teaches you to observe all of your instruments! 👍

**Pull request merged**
