### PR TITLE
Various cockpit improvements

### PR DESCRIPTION
**Pull request by hbeni**
This This evening i improved the cockpit alot.
#128 is fixed, the radio stack now operates like in the c172 with MUCH more userfriendlyness.
#149 is mostly fixed, however the Garmin device is still not operable. This should be tackled in a separate issue that i opened just now.

Please test :)

### CODE REVIEW

**Comment by hbeni** [comment]
@gilbertohasnofb It seems that the KN62 ADF radio is too dark; where/how can i adjust the baseline illumination?
image

**Comment by HHS81** [comment]
@hbeni change the material settings in the .ac-model. (via text editing)

**Comment by hbeni** [comment]
Ok, thanks, fixed this in commit 870da5e

**Comment by hbeni** [comment]
Ok, i think this is ready to merge now.
@HHS81 If you give your OK, i will merge this into master.

**Pull request merged**
