### PR TITLE
Issue248

### LINKED ISSUE #248: Add a flashlight and radiance effect
Port the ALS flashlight

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #248 

This is finished as far as I am concerned and ready to merge.

### CODE REVIEW

**Comment by HHS81** [comment]
@wlbragg 

Effects don't need to be relative. Like Thorsten I prefere absolute paths for debugging. See: https://sourceforge.net/p/flightgear/mailman/message/35725462/

Adding the white.png not need since it isn't used by any effect here.

**Comment by HHS81** [comment]
@wlbragg 
Thanks!
I know that some developers prefer relatives paths, some like me absolute paths. The point by the User jsb doesn't really count for me by using GIT or SVN. 

So many thanks for the changes again and for your hard work, it looks great! I will merge it, and try to commit it to FGAddon (there are some issue at sourceforge...)

**Comment by wlbragg** [comment]
>Effects don't need to be relative. 

I originally did that because of the black fuselage effect I was getting. I thought it was caused by my directory structure. As far as relative VS absolute in general, I always prefer relative. Absolute paths get you in trouble when your code and files are subject to non-standard directory structures which mine tend to be. But for this, no problem, as you wish.

white.png was only nedded if flashlight effect was not using the shadow cubes.

Speaking of
>black fuselage effect I was getting

Also there is a duplicate ambient-correction
~~~
<reflection-enabled type="int">1</reflection-enabled>
<reflect-map-enabled type="int">1</reflect-map-enabled>
<reflection-correction type="float"><use>/sim/rendering/refl_correction</use></reflection-correction>
<reflection-fresnel-factor type="float"><use>/sim/rendering/fresnel-factor</use></reflection-fresnel-factor>
<reflection-type type="int"><use>/sim/rendering/refl-type</use></reflection-type>
<reflection-dynamic type="int">1</reflection-dynamic>
<ambient-correction type="float"><use>/sim/rendering/ambient_correction</use></ambient-correction>
[snip]
<reflection-rainbow type="float">0.0</reflection-rainbow>
<reflection-noise type="float">0.0</reflection-noise>
<ambient-correction type="float">0.1</ambient-correction>
<dirt-enabled type="int">0</dirt-enabled>
<dirt-color type="vec3d">1.0 1.0 1.0</dirt-color>
<dirt-factor type="float">0.5</dirt-factor>
~~~

Also in c182s-set.xml...
~~~
<refl_correction type="string">-0.5</refl_correction>
<ambient_correction type="string">0.1</ambient_correction>
<refl-type>1.0</refl-type>
<fresnel-factor>0.7</fresnel-factor>
~~~
should be...
~~~
<refl_correction type="float">-0.5</refl_correction>
<ambient_correction type="float>0.1</ambient_correction>
<refl-type type="int>1</refl-type>
<fresnel-factor type="float>0.7</fresnel-factor>
~~~

**Comment by HHS81** [comment]
@wlbragg 

>  non-standard directory structures

How does they look?

The type definitions comes from former effect files, I will change them in master

**Comment by wlbragg** [comment]
>Isn't the Effects/model-transparent one an FG standard effect?

Yes. We need to put this back to...

~~~
   <effect>
    <inherits-from>Effects/model-transparent</inherits-from>
    <object-name>SunVirsor.R</object-name>
    <object-name>SunVirsor.L</object-name>
    <object-name>FuelFlowL.Ann</object-name>
    <object-name>FuelFlow.Ann</object-name>
    <object-name>FuelFlowR.Ann</object-name>
    <object-name>PitchTrim.Ann</object-name>
     <object-name>OilPress.Ann</object-name>
    <object-name>VACL.Ann</object-name>
    <object-name>VAC.Ann</object-name>
    <object-name>VACR.Ann</object-name>
    <object-name>Volts.Ann</object-name>
   </effect>
~~~

@HHS81 how do we want to do this? Push a new branch and PR?

**Comment by hbeni** [comment]
fixed it and pushed it to the already existing branch (reopening the PR)

**Pull request merged**
